format = """
$username\
$directory\
$character
"""
right_format = """| $all """

[directory]
truncation_length = 2

[hostname]
ssh_symbol = " "
format = "[$ssh_symbol $hostname]($style) "

[git_branch]
symbol = ""
format =  "[$symbol $branch (:$remote_branch)]($style)"

[git_status]
style = "blue"
format = "[$modified$deleted$untracked$ahead_behind]($style) "
modified = " "
deleted = " "
untracked = " "
ahead = " "
behind = " "
up_to_date = " "

[cmd_duration]
min_time = 20_000

[sudo]
style = "white"
format = "[$symbol]($style) "
symbol = ""
disabled = false

[custom.docker]
style = "grey"
format = "[$symbol]($style) "
symbol = " "
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]

[username]
show_always = true
style_user = "bold white"
style_root = "bold white"
format = '[ $user ]($style)'

[directory.substitutions]
"Documentos" = "󰈙 "
"Descargas" = " "
"Música" = "󰝚 "
"Imágenes" = " "

[nodejs]
symbol = ""
style = "white"
format = '[$symbol($version)]($style)'

[python]
style = "yellow"
format = "via [${symbol} ${pyenv_prefix}(${version}) $virtualenv ]($style)"
symbol = ""
detect_extensions = []
detect_files = ["__init__.py", "requirements.txt", "pyproject.toml", "setup.py"]

[c]
symbol = " "
style = "white"
format = '[ $symbol( $version) ]($style)'

[cpp]
symbol = " "
style = "white"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "white"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "white"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "white"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = ""
style = "white"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "white"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "white"
format = '[ $symbol( $version) ]($style)'

[docker_context]
symbol = ""
style = "white"
format = '[ $symbol( $context) ]($style)'

[conda]
style = "white"
format = '[ $symbol( $environment) ]($style)'

[pixi]
style = "white"
format = '[ $symbol( $version)( $environment) ]($style)'