"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color1)\
$os\
$username\
[](bg:color4 fg:color1)\
$directory\
[](fg:color4 bg:color6)\
$git_branch\
$git_status\
[](fg:color6 bg:color1)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color1 bg:bg2)\
$docker_context\
$conda\
$pixi\
[](fg:bg2 bg:bg)\
$time\
[ ](fg:bg)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
fg = '#ffffff'
bg = '#5d596c'
bg2 = '#c66ec3'
color1 = '#6d70d2'
color6 = '#738ee2'
color4 = '#c66ec3'
white = '#ffffff'
color_green = '#98971a'
color_red = '#cc241d'

[os]
disabled = false
style = "bg:color1 fg:fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color1 fg:fg"
style_root = "bg:color1 fg:fg"
format = '[ $user ]($style)'

[directory]
style = "fg:fg bg:color4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color6"
format = '[[ $symbol $branch ](fg:fg bg:color6)]($style)'

[git_status]
style = "bg:color6"
format = '[[($all_status$ahead_behind )](fg:fg bg:color6)]($style)'

[nodejs]
symbol = ""
style = "bg:color1"
format = '[[ $symbol( $version) ](fg:fg bg:color1)]($style)'

[c]
symbol = " "
style = "bg:color1"
format = '[[ $symbol( $version) ](fg:fg bg:color1)]($style)'

[cpp]
symbol = " "
style = "bg:color1"
format = '[[ $symbol( $version) ](fg:fg bg:color1)]($style)'

[rust]
symbol = ""
style = "bg:color1"
format = '[[ $symbol( $version) ](fg:fg bg:color1)]($style)'

[golang]
symbol = ""
style = "bg:color1"
format = '[[ $symbol( $version) ](fg:fg bg:color1)]($style)'

[php]
symbol = ""
style = "bg:color1"
format = '[[ $symbol( $version) ](fg:fg bg:color1)]($style)'

[java]
symbol = ""
style = "bg:color1"
format = '[[ $symbol( $version) ](fg:fg bg:color1)]($style)'

[kotlin]
symbol = ""
style = "bg:color1"
format = '[[ $symbol( $version) ](fg:fg bg:color1)]($style)'

[haskell]
symbol = ""
style = "bg:color1"
format = '[[ $symbol( $version) ](fg:fg bg:color1)]($style)'

[python]
symbol = ""
style = "bg:color1"
format = '[[ $symbol( $version) ](fg:fg bg:color1)]($style)'

[docker_context]
symbol = ""
style = "bg:bg2"
format = '[[ $symbol( $context) ](fg:#83a598 bg:bg2)]($style)'

[conda]
style = "bg:bg2"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:bg2)]($style)'

[pixi]
style = "bg:bg2"
format = '[[ $symbol( $version)( $environment) ](fg:fg bg:bg2)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:bg"
format = '[[  $time ](fg:fg bg:bg)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[╰─](bold fg:color_green)'
error_symbol = '[╰─](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:white)'
vimcmd_replace_symbol = '[](bold fg:white)'
vimcmd_visual_symbol = '[](bold fg:color4)'